@main
enum CheckMain {
    static func main() {
        SentenceBufferChecks.run()
        VADLogicChecks.run()
        HermesSSEParserChecks.run()
        HotkeyKeyMapChecks.run()
        GradiumSTTChunkingChecks.run()
        GradiumTTSWireChecks.run()
        GradiumTTSSynthesizeChecks.run()
        TTSChunkBufferChecks.run()
        STTCommitChecks.run()
        BuddyLayoutChecks.run()
        AnnotateOverlayChecks.run()
        AnnotatePromptChecks.run()
        HermesSystemPromptChecks.run()
        HermesReplyFilterChecks.run()
        MarkdownDisplayChecks.run()
        HermesHTTPErrorChecks.run()
        ObsidianNotesChecks.run()
        HarnessKindChecks.run()
        AppConfigHarnessChecks.run()
        OnboardingChecks.run()
        LastUserTextChecks.run()
        CLIBinaryChecks.run()
        InfoPlistChecks.run()
        ClaudeStreamParserChecks.run()
        ClaudeCLIArgsChecks.run()
        ClaudeSessionFilesChecks.run()
        CodexStreamParserChecks.run()
        CodexCLIArgsChecks.run()
        HermesSessionURLChecks.run()
        PinnedSessionStoreChecks.run()
        BackgroundClearGateChecks.run()
        print("all checks passed")
    }
}
